### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by GiovanH** [mindcruzer/pelican-encrypt-content#19]
Doesn't seem to support python 3 types, test file outputs

```
$ python3 test_encrypt_content.py
EE
======================================================================
ERROR: test_encrypt_text_aes (__main__.TestEncryptContent)
Verify that the ciphertext is actually decryptable.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_encrypt_content.py", line 36, in test_encrypt_text_aes
    self.assertEqual(plaintext.decode('utf-8').rstrip(padding_char), text)
TypeError: rstrip arg must be None or str

======================================================================
ERROR: test_hash_md5 (__main__.TestEncryptContent)
Verify that md5 hashes are being computed correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_encrypt_content.py", line 19, in test_hash_md5
    self.assertEqual(md5_bytes.encode('hex'), '098f6bcd4621d373cade4e832627b4f6')
AttributeError: 'bytes' object has no attribute 'encode'

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=2)
```

**Comment by mindcruzer** [comment]
Pull the most recent changes, these issues have been fixed.
